image: gradle:4.7-jdk8-alpine

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

Build:
  stage: build
  script:
    - gradle clean build --refresh-dependencies

Test:
  stage: test
  script:
    - gradle check
    - gradle jacocoTestReport
    - gradle jacocoTestCoverageVerification

DeployProduction:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=testinglinebot1 --api-key=5e8d6665-e3c2-427c-b0f1-f0324abd8e24
  when: manual
  environment:
    name: production
    url: https://testinglinebot1.herokuapp.com/
